remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false # (unquoted) to indicate whether to provide a download URL
# google_analytics: [Your Google Analytics tracking ID]
title: lnau.net
description: A bitcoin lightning network routing node.
github:
 repository_url: https://lnau.net
